insert into silverlijk.observations
(   id, 
	barometricPressure, 
	cloudLayers, 
	dewpoint, 
	elevation, 
	heatIndex, 
	icon, 
	maxTemperatureLast24Hours, 
	minTemperatureLast24Hours, 
	precipitationLast3Hours, 
	precipitationLast6Hours, 
	precipitationLastHour, 
	presentWeather, 
	rawMessage, 
	relativeHumidity, 
	seaLevelPressure, 
	stationId, 
	stationName, 
	temperature, 
	textDescription, 
	timestamp, 
	visibility, 
	windChill, 
	windDirection, 
	windGust, 
    windSpeed,
	geometry)
SELECT concat(bo.properties.stationId, string(bo.properties.timestamp)) as id, 
	bo.properties.barometricPressure, 
	bo.properties.cloudLayers, 
	bo.properties.dewpoint, 
	bo.properties.elevation, 
	bo.properties.heatIndex, 
	bo.properties.icon, 
	bo.properties.maxTemperatureLast24Hours, 
	bo.properties.minTemperatureLast24Hours, 
	bo.properties.precipitationLast3Hours, 
	bo.properties.precipitationLast6Hours, 
	bo.properties.precipitationLastHour, 
	bo.properties.presentWeather, 
	bo.properties.rawMessage, 
	bo.properties.relativeHumidity, 
	bo.properties.seaLevelPressure, 
	bo.properties.stationId, 
	bo.properties.stationName, 
	bo.properties.temperature, 
	bo.properties.textDescription, 
	bo.properties.timestamp, 
	bo.properties.visibility, 
	bo.properties.windChill, 
	bo.properties.windDirection, 
	bo.properties.windGust, 
	bo.properties.windSpeed,
    geometry from bronzey.observations bo
left anti join silverlijk.observations so on 
    concat(bo.properties.stationId, string(bo.properties.timestamp))=so.id
